name: Upstream reference checks
on:
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+
defaults:
  run:
    shell: bash
jobs:
  upstream-refs:
    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000
    name: Upstream reference checks
    steps:
      - name: Checkout addon controller
        uses: actions/checkout@v5
        with:
          path: governance-policy-addon-controller
      - name: Checkout Policy Framework
        uses: actions/checkout@v5
        with:
          path: governance-policy-framework
          repository: stolostron/governance-policy-framework
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: governance-policy-framework/go.mod
          cache-dependency-path: governance-policy-framework/go.sum
      - name: Detect upstream references that should be replaced
        working-directory: governance-policy-addon-controller
        run: >
          ./../governance-policy-framework/build/detect-upstream.sh -m "cat Makefile" -i "go list -mod readonly -m all" 
          -q "config/manager/manager.yaml"
          -q "pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml"
          -q "pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml"
          -q "pkg/addon/policyframework/manifests/managedclusterchart/values.yaml"
