name: Upstream reference checks

on:
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+

defaults:
  run:
    shell: bash

jobs:
  kind-tests:
    runs-on: ubuntu-latest
    env:
      REGISTRY: localhost:5000

    name: Upstream reference checks
    steps:
    - name: Checkout addon controller
      uses: actions/checkout@v2
      with:
        path: governance-policy-addon-controller
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Checkout Policy Framework
      uses: actions/checkout@v2
      with:
        path: governance-policy-framework
        repository: stolostron/governance-policy-framework
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: '1.18'

    - name: Detect upstream references that should be replaced
      working-directory: governance-policy-addon-controller
      run: >
        ./../governance-policy-framework/build/detect-upstream.sh -m "cat Makefile" -i "go list -mod readonly -m all" 
        -q "config/manager/manager.yaml"
        -q "pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml"
        -q "pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml"
        -q "pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml"
        -q "pkg/addon/policyframework/manifests/managedclusterchart/values.yaml"
